### ISSUE TITLE
[feat] Add yup validation to form

### ISSUE THREAD

**Issue by DeadEnglish** [DeadEnglish/openai-playground#1]
** Issue **
Currently, there's 0 validation on the form and it can be submitted without adding a topic.

** Todo **
- [ ] remove default values `style` and `targetAudience` from initial values
- [ ] remove `maxLength` from formik form types
- [ ] add validation to make all form values required
- [ ] add validation messages and handling
